language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
matrix:
  include:
    - perl: "5.18"
      env: WITH_TIME_FAKE=1

before_install:
  - '[ "$WITH_TIME_FAKE" = 1 ] && cpanm --quiet --notest Time::Fake || true'

branches:
  except:
    - /appveyor/
sudo: false
