language: perl
matrix:
  include:
    - perl: "5.22"
      env: WITH_TIME_FAKE=1
    - perl: "5.8"
      env: WITH_TIME_FAKE=1
    - perl: "5.20"
    - perl: "5.18"
    - perl: "5.18"
      env: WITH_TIME_FAKE=1
    - perl: "5.16"
    - perl: "5.14"
    - perl: "5.12"
    - perl: "5.10"

before_install:
  - '[ "$WITH_TIME_FAKE" = 1 ] && cpanm --quiet --notest Time::Fake || true'

branches:
  except:
    - /appveyor/
sudo: false
