branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" cinst --allow-empty-checksums strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
# Try to install Tk with PPM first, as it's much faster
  - ppm install Tk
  - cpanm --installdeps .
  - cpanm --notest Time::Fake

build_script:
  - perl Makefile.PL
  - gmake test
